color: null
fieldLayouts:
  9c6b7761-3972-4ee2-8e17-8a00cbd88e7e:
    cardView:
      - dateCreated
      - dateUpdated
      - slug
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-01T15:08:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: aa1c5e7c-b908-45a2-90c4-95eed33dc70c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-02T15:08:04+00:00'
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: summary
            includeInCards: false
            instructions: 'Summary of the Article.'
            label: Summary
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75a838eb-f649-4182-918c-645a4c27204a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-01T15:12:06+00:00'
            elementCondition: null
            fieldUid: 7f0dd947-99d8-4456-93f3-4ce4f6162a3f # Rich Text - Simple
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8e5bfd0d-6a3a-4e5e-aa02-be9847e3da05
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-01T15:12:06+00:00'
            elementCondition: null
            fieldUid: 5cbe08b7-b4bd-4a6b-be41-de9647b5eb19 # Images
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a66fc91a-896e-4de3-9667-6282c8e5fa8d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-02T15:08:48+00:00'
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: mainImage
            includeInCards: false
            instructions: null
            label: 'Main Image'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8a0b6e9a-b467-4a08-b82b-bc3455061545
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9acfe50c-6d79-48d1-aceb-5474b57a834a
        userCondition: null
handle: blogPost
hasTitleField: true
icon: null
name: 'Blog Post'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
