color: null
fieldLayouts:
  aaa37ed7-f707-4ae2-a24a-793f4394a858:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-09T18:57:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 74e29f11-3c49-4e0c-ba0a-aa8719cacafc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f446d3e3-bab8-47a5-92b1-c47a74f9679f
        userCondition: null
handle: bridgeSectionTitle
hasTitleField: true
icon: null
name: 'Bridge Section Title'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
