color: null
fieldLayouts:
  a38df012-82a1-44d6-b096-4355f5438624:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-09T19:33:58+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6662e3a6-0dd7-4b5e-b4eb-7916242a9a89
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-09T19:38:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d39957ab-68e1-40e5-b7cc-a59e3c8459f4 # Subtitle
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f0f74a9-dfe8-461a-8b92-ad4460375db1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-09T19:38:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: paragraph
            includeInCards: false
            instructions: null
            label: Paragraph
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ecaee373-36d9-4ae5-bdbf-525ceeb80bdb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-09T19:38:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6d792fe4-471d-48ed-bc45-5fe112ba7e46 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a4f2f9c-f411-4b29-b78d-5bb693265d46
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-09T19:38:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: df3ef6aa-107e-40f0-82f4-de195ff3dfc0 # Image Placement
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1dc5aaa3-def7-4fc3-932c-3fc3fc5614ab
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5e94547d-224f-4dcb-9fa6-cc2a202dff87
        userCondition: null
handle: imageAndTextSection
hasTitleField: true
icon: null
name: 'Image and Text Section'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
