color: null
fieldLayouts:
  3fe2559a-6382-48d6-95fd-731651ad1965:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-10T15:17:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 42eea3c2-2f84-43d8-a495-647d4994a8d5 # Text - Multiline
            handle: quote
            includeInCards: false
            instructions: null
            label: Quote
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f1e72289-0b68-42c2-8aff-a9f152093ab8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-10T15:17:43+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f3e544b8-88bf-4761-8df2-d767fa1502b7 # Text
            handle: quoter
            includeInCards: false
            instructions: null
            label: Author
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c86ebb16-f1ce-46ef-b6e4-1c302b9171dd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3dc0b23c-6de8-4451-b9c1-d07bd7b98ba5
        userCondition: null
handle: quote
hasTitleField: false
icon: null
name: Quote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
