color: null
fieldLayouts:
  083ea289-b705-4ceb-83fc-230912be7ce5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-09T18:30:21+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2bf89eed-adeb-4a46-aa7d-04f3cf330b9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: de7dfe04-8715-44a0-aadc-f79ddb5da62d
        userCondition: null
handle: sectionTitle
hasTitleField: true
icon: null
name: 'Section Title'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
