color: null
fieldLayouts:
  1edbfe34-63ab-446e-895b-563d51ecabf9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-09T19:11:48+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d3e4e3f8-451e-4412-90e3-d3db0d6c3506
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5bed1e12-897c-4f57-88e6-5e2c27f2bdea
        userCondition: null
handle: sectionTitleTwo
hasTitleField: true
icon: null
name: 'Section Title'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
