color: null
fieldLayouts:
  d670d8a3-7117-4a66-a107-8f962d7f6b12:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-10T19:27:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 6c0a7822-27f7-4cea-877f-f59e66186b2b # iFrame URL
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c470dff3-57df-40b5-a457-37cf756b4c42
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-10T19:28:39+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2b4083bb-af25-45dd-8133-494a15a3ec62 # Text Array
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8becb706-d0ac-4f7e-9249-ecd23969d2f2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0df3e9e8-6464-49bd-8ad1-13b2d5cea949
        userCondition: null
handle: videoContent
hasTitleField: false
icon: null
name: 'Video Content'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
