altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  716adc21-0eff-4024-8800-91b62629461e:
    cardView:
      - dateUpdated
      - dateCreated
      - kind
      - size
      - filename
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-03-28T20:09:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 03fd257e-6dfd-4042-bc65-9f3f318901f0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6d679841-5788-411b-91fa-7d4300039fef
        userCondition: null
fs: local
handle: videos
name: Videos
sortOrder: 3
subpath: videos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: local
transformSubpath: videos
