dateModified: 1754858592
email:
  fromEmail: $CRAFT_SYSTEM_EMAIL
  fromName: $CRAFT_SITE_NAME
  replyToEmail: null
  template: _emails/system.twig
  transportSettings:
    apiKey: $MAILGUN_API_KEY
    domain: $MAILGUN_DOMAIN
    endpoint: $MAILGUN_ENDPOINT
  transportType: craft\mailgun\MailgunAdapter
fs:
  local:
    hasUrls: true
    name: Local
    settings:
      path: $FILESYSTEM_LOCAL_BASE_PATH
    type: craft\fs\Local
    url: $FILESYSTEM_LOCAL_BASE_URL
  servd:
    hasUrls: true
    name: Servd
    settings:
      cdnUrlPattern: ''
      customSubfolder: ''
      makeUploadsPublic: true
      optimisePrefix: ''
      optimiseUrlPattern: ''
      projectSlug: ''
      securityKey: ''
      subfolder: /local/
    type: servd\AssetStorage\AssetsPlatform\Fs
    url: 'https://cdn2.assets-servd.host/'
meta:
  __names__:
    0b199c11-0b79-4e4b-b931-f9c85e23a667: 'Link / Button' # Link / Button
    2b4083bb-af25-45dd-8133-494a15a3ec62: 'Text Array' # Text Array
    2d46210c-fa5d-4be1-9b9a-039660a6f412: 'Social Content' # Social Content
    2dc2adb0-b7a5-4caf-ac5f-a12d60851e1f: 'Segement Title' # Segement Title
    2e3676cf-7394-40ab-a6a5-c1504ad79b3a: Page # Page
    2f9a47e6-406d-40df-bc4c-79b4c88b70eb: 'Quote Section' # Quote Section
    5b174668-2d43-41e7-8a70-37d340db94a6: Community # Community
    5cbe08b7-b4bd-4a6b-be41-de9647b5eb19: Images # Images
    6c0a7822-27f7-4cea-877f-f59e66186b2b: 'iFrame URL' # iFrame URL
    6d792fe4-471d-48ed-bc45-5fe112ba7e46: Image # Image
    7bf65ac5-9169-4bf8-8825-65fadd566946: New # New
    7f0dd947-99d8-4456-93f3-4ce4f6162a3f: 'Rich Text - Simple' # Rich Text - Simple
    08acd02d-15d4-4039-8675-8c87cfc48082: 'Section Title' # Section Title
    08b3d8c1-d275-47cc-884d-d868738972b2: 'Text Array Item' # Text Array Item
    8b610edc-f2dd-46b6-9597-96fcbb6d302a: Simple # Simple
    08c386f4-5a41-4c9f-8282-f6785af06bfc: bridge-association # bridge-association
    19a41df1-af8c-4978-9247-b64c01c56535: 'Section Title & Bridge Segments' # Section Title & Bridge Segments
    19d6d897-1cde-4d59-914a-2bf8a23e7916: 'Public Schema' # Public Schema
    21ae5ec3-ab6e-4d85-8720-fb22957a84ef: 'Horizontal Image and Text' # Horizontal Image and Text
    42eea3c2-2f84-43d8-a495-647d4994a8d5: 'Text - Multiline' # Text - Multiline
    53a2d1d4-d3c4-4005-9d3f-f2b053c40dfa: 'Contact Email' # Contact Email
    56cfd589-eea7-4bc3-bc19-14038349a3c2: 'Image and Text Section' # Image and Text Section
    81c99547-d10c-4044-bba9-dca0094a6c1e: Blog # Blog
    88e751b6-6437-403c-a814-407524c7853a: Quote # Quote
    111f4f1f-9016-491b-92cf-98f56f69170f: 'Contact Email' # Contact Email
    376ac35e-8420-49ec-831c-1731d7358df8: Social # Social
    453f9294-407d-405a-b73b-d5b63aec2eaa: SEO # SEO
    502c0610-e74d-4359-8524-5652307ada64: Padding # Padding
    714e1c2e-f7c6-4e9b-a0d3-3bfb602421b0: Blog # Blog
    1061d0dc-0197-4b41-8c62-f728d5842b4d: 'Quirky Emporium' # Quirky Emporium
    2425b6d7-525a-48e8-aaf3-e4c799c6721e: Summary # Summary
    06406c4d-57f8-442f-a995-ac844b034b01: Training # Training
    6471f106-123c-4b33-a20b-69e939beb932: 'Social Link' # Social Link
    8530d0ec-da25-49ff-ab0f-0b85e5ecb015: 'Bridge Section Title' # Bridge Section Title
    8688ce9b-bba1-41ab-a820-89974a14cb5d: 'Bridge Section' # Bridge Section
    77111d2d-eb09-4957-9930-0c2bfd3d95e0: 'Contact Number' # Contact Number
    800713f2-8d8c-406b-9fcc-91d23720c068: 'Contact Number' # Contact Number
    8037477b-d2a5-4174-8fc2-2d62637f795b: Home # Home
    9755366f-6d87-48af-aa16-a2c921387368: HomePage # HomePage
    a54c6c81-5622-4a97-85e7-d5cda39454be: Videos # Videos
    b5cc6221-471c-4d71-b0ec-3af30ddc5364: Page # Page
    b9ac68e1-d9f1-4007-843f-fde1e9f4921b: Files # Files
    b81ebc1a-eb6c-4822-9a3d-3103de89b902: 'Video Section' # Video Section
    b1468b9d-2d8d-4882-94cf-833f64df1381: 'Hug a Mug' # Hug a Mug
    bdf6317d-0df7-449f-a937-a1a274ffb106: 'Page - Blocks' # Page - Blocks
    be5429a3-63db-4f88-b70d-f3f4e302d6fb: 'Section Title' # Section Title
    bea45cde-7d9a-4c7c-b250-2a2f165b102a: Videp # Videp
    c99e9b57-2927-493f-8af6-d09f03e6e2e2: Address # Address
    cb6226c7-5901-41ed-ba28-a78b9504a3df: Images # Images
    cbc81bdc-e5e5-4dab-8721-f77217d0ad0d: 'Blog Post' # Blog Post
    cbfce732-a7d7-4aa4-ae48-c841b8fae9fd: 'Bridge Segments' # Bridge Segments
    d4f0b259-8f40-41f3-9289-78e6476a6c79: 'Bridge Segment' # Bridge Segment
    d45c2d99-2978-4dcc-9d01-8bdaea2043ad: Address # Address
    d81c7e1d-7f2e-4ca1-a6cd-df45e897f566: 'Social Links' # Social Links
    d99bf7af-1eb1-4b77-814e-624eeec1a0e3: $CRAFT_SITE_NAME # $CRAFT_SITE_NAME
    d39957ab-68e1-40e5-b7cc-a59e3c8459f4: Subtitle # Subtitle
    da9f3d8e-5ba9-4eb9-a423-6ea09ddaed21: Form # Form
    df3ef6aa-107e-40f0-82f4-de195ff3dfc0: 'Image Placement' # Image Placement
    e2a4e8c8-440e-4087-b7f4-ee93baa3ca0e: 'Video Content' # Video Content
    f3e544b8-88bf-4761-8df2-d767fa1502b7: Text # Text
    fb0420bb-0fbf-46d2-afd2-f7992c60c886: 'Contact Form' # Contact Form
plugins:
  blitz:
    edition: standard
    enabled: true
    licenseKey: XO8E4093H0FPPEWU31U2S5HZ
    schemaVersion: 5.11.0
    settings:
      maxUriLength: 2048
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  mailgun:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 795D0IRXMO0BEU95Z64ILX03
    schemaVersion: 3.0.13
  servd-asset-storage:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      adjustFeedmeLogs: ''
      assetsEnvironment: $SERVD_ASSET_ENVIRONMENT
      assetsEnvironmentOverwrite: ''
      cacheClearMode: full
      clearCachesOnSave: never
      disableDynamic: ''
      disableTransforms: ''
      fsMapsEnabled: ''
      imageAutoConversion: webp
      injectCors: '1'
      projectSlug: $SERVD_PROJECT_SLUG
      securityKey: $SERVD_SECURITY_KEY
      suppressWarnings: '1'
      useLocalVolumes: false
  sprig:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $CRAFT_SITE_NAME
  retryDuration: null
  schemaVersion: 5.7.0.3
  timeZone: America/Los_Angeles
