fieldLayouts:
  98d5ac7b-b243-4a04-83b5-fb2a53817877:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-10T20:36:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 2d46210c-fa5d-4be1-9b9a-039660a6f412 # Social Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37e16ae1-53e4-4847-a6d3-af89ecbff4e2
            userCondition: null
            warning: null
            width: 100
        name: Socials
        uid: d226bbda-3f26-49b8-89f2-a3eb587a4397
        userCondition: null
handle: socialLinks
name: 'Social Links'
sortOrder: 1
