defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: cbc81bdc-e5e5-4dab-8721-f77217d0ad0d # Blog Post
handle: blog
maxAuthors: 1
name: Blog
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  08c386f4-5a41-4c9f-8282-f6785af06bfc: # bridge-association
    enabledByDefault: true
    hasUrls: true
    template: _pages/blog/entry.twig
    uriFormat: 'blog/{slug}'
type: channel
